# Generated by Django 4.1.6 on 2023-03-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('hospital_selection', models.CharField(max_length=255)),
                ('accident_place', models.CharField(max_length=255)),
                ('patient_status', models.CharField(max_length=1000)),
            ],
        ),
    ]
